workingDirectory: "C:/Users/oshen/AnypointStudio/studio-workspace/"

folder:
  path: "/src/main/resources/config/"
  mule:
    path: "/src/main/mule/"
    
api:
  exclusions: ["^.*api-main.*", "^.*api-console.*", "^.*mckesson-mule-common.*"]
  namesConversion: '{"foe-bidwh-sa":"b2b-foe-bidwh-system-api","foe-mnetics-sa":"b2b-foe-mnetics-system-api","foe-remtp-sa":"b2b-foe-remtp-system-api","foe-sfdc-sa":"b2b-foe-sfdc-system-api","sap-account-pa":"b2b-sap-account-process-api","sap-asn-pa":"b2b-sap-asn-process-api","sap-invoice-portal-sa":"b2b-sap-invoice-portal-system-api","sap-order-pa":"b2b-sap-order-process-api","sap-price-pa":"b2b-sap-price-process-api","sap-product-pa":"b2b-sap-product-process-api","sap-sfdc-ea":"b2b-sap-sfdc-experience-api","sap-sfdc-sa":"b2b-sap-sfdc-system-api","sap-supplier-pa":"b2b-sap-supplier-process-api","sap-tpos-sa":"b2b-sap-tpos-system-api","sap-vendor-pa":"b2b-sap-vendor-process-api","suplier-point-sa":"b2b-supplier-point-db-system-api","order-pa":"b2b-hub-order-process-api","remtp-sa":"b2b-hub-remtp-system-api","sfdc-ea":"b2b-hub-sfdc-experience-api","sfdc-sa":"b2b-hub-sfdc-system-api","van-schedule-pa":"b2b-hub-van-schedule-process-api","contract-pa":"b2b-hub-contract-process-api","bi-reports-pa":"b2b-hub-bi-reports-process-api","bi-reports-sa":"b2b-hub-bi-reports-system-api","supplier-pa":"b2b-hub-supplier-process-api","mapping-pa":"b2b-hub-mapping-process-api","complete-generics-sa":"b2b-hub-complete-generics-system-api","barcode-sa":"b2b-hub-barcode-system-api","profile-sa":"b2b-hub-profile-system-api","profile-pa":"b2b-hub-profile-process-api","price-pa":"b2b-hub-price-process-api","asn-pa":"b2b-hub-asn-process-api","ingres-sa":"b2b-hub-ingres-system-api","account-pa":"b2b-hub-account-process-api","sfdc-sa":"b2b-hub-sfdc-system-api","product-pa":"b2b-hub-product-process-api","s4-eu-right-to-buy-sa":"sap-api","s4-eu-stat-against-target-sa":"sap-api","s4-eu-credit-info-sa":"sap-api","s4-eu-custrebatereport-sa":"sap-api","s4-eu-invoice-cred-deb-sa":"sap-api","s4-eu-salesorder-sa":"sap-api","s4-eu-vendor-pricing-sa":"sap-api","s4-eu-recall-list-sa":"sap-api","s4-eu-backing-data-sa":"sap-api","s4-eu-purchaseorder-sa":"sap-api","s4-eu-settlement-files-sa":"sap-api","s4-eu-supplier-stocklevel-sa":"sap-api","s4-eu-customer-return-sa":"sap-api","s4-eu-stock-report-sa":"sap-api","s4-eu-movingaverageprice-sa":"sap-api"}'
  
projects:
  #namelist: ["b2b-foe-bidwh-system-api","b2b-foe-mnetics-system-api","b2b-foe-remtp-system-api","b2b-foe-sfdc-system-api","b2b-sap-account-process-api","b2b-sap-asn-process-api","b2b-sap-invoice-portal-system-api","b2b-sap-order-process-api","b2b-sap-price-process-api","b2b-sap-product-process-api","b2b-sap-sfdc-experience-api","b2b-sap-sfdc-system-api","b2b-sap-supplier-process-api","b2b-sap-tpos-system-api","b2b-sap-vendor-process-api","b2b-supplier-point-db-system-api","b2b-hub-account-process-api","b2b-hub-ingres-system-api","b2b-hub-order-process-api","b2b-hub-remtp-system-api","b2b-hub-sfdc-experience-api","b2b-hub-sfdc-system-api","b2b-hub-van-schedule-process-api","b2b-hub-contract-process-api"]
  #namelist: ["b2b-hub-contract-process-api","b2b-hub-bi-reports-process-api","b2b-hub-bi-reports-system-api","b2b-hub-supplier-process-api","b2b-hub-mapping-process-api","b2b-hub-complete-generics-system-api","b2b-hub-barcode-system-api","b2b-hub-profile-system-api","b2b-hub-profile-process-api","b2b-hub-price-process-api","b2b-hub-asn-process-api"]
  namelist: ["b2b-hub-account-process-api"]
  
property:
  fileList: ["local-properties.yaml","dev-properties.yaml","qa-properties.yaml","uat-properties.yaml","prod-properties.yaml"]
  exclusions: ["b2b-hub-bi-reports-process-api_uat-properties.yaml","b2b-hub-bi-reports-system-api_uat-properties.yaml"]
  
descriptions: [
  "api.version - version of created API",
  "autodiscovery.api.id - id of created API in API Manager for pairing with the deployed application on the platform",
  "http.listener.path - base api part of url",
  "mule.username - mulesoft user name account",
  "mule.password - password for mulesoft user account",
  "db.host - database host IP address",
  "db.port - database port number",
  "db.instance - database instance",
  "db.user - database user name",
  "db.password - database user password",
  "http.foe-mnetics.host - host of foe-mnetics server to connect to",
  "http.foe-mnetics.port - foe-mnetics server port number",
  "http.foe-mnetics.basePath - foe-mnetics server api part of url",
  "http.foe-mnetics.timeout - foe-mnetics server timeout in milliseconds",
  "http.foe-mnetics.username - foe-mnetics server user name",
  "http.foe-mnetics.password - foe-mnetics user password",
  "http.remtp.host - host of remtp server to connect to",
  "http.remtp.port - remtp server port number",
  "http.remtp.basePath - remtp server api part of url",
  "http.remtp.timeout - remtp server timeout in milliseconds",
  "http.remtp.fields - remtp server fields",
  "http.remtp.routing - remtp server routing for specific branch ids",
  "remtp.host - host of remtp server to connect to",
  "remtp.timeout - remtp server timeout in milliseconds",
  "remtp.stock-availability.port - remtp stock-availability integration server port number",
  "remtp.stock-availability.method - remtp stock-availability integration server method name to call",
  "remtp.stock-availability-star-k.port - remtp stock-availability-star-k integration server port number",
  "remtp.stock-availability-star-k.method - remtp stock-availability-star-k integration server method name to call",
  "remtp.stock-availability-obtain.port - remtp stock-availability-obtain integration server port number",
  "remtp.stock-availability-obtain.method - remtp stock-availability-obtain integration server method name to call",
  "remtp.live-stock.port - remtp live-stock integration server port number",
  "remtp.live-stock.method - remtp live-stock integration server method name to call",
  "remtp.place-order.default-host - default host of remtp place-order integration server to connect to",
  "remtp.place-order.default-port - default remtp place-order integration server port number",
  "remtp.place-order.default-po-port - default po remtp place-order integration server port number",
  "remtp.place-order.v007-host - host of remtp place-order integration server of version 007 to connect to",
  "remtp.place-order.v008-host - host of remtp place-order integration server of version 008 to connect to",
  "remtp.place-order.v009-host - host of remtp place-order integration server of version 009 to connect to",
  "remtp.place-order.getListBranches - list of remtp place-order integration branches",
  "remtp.place-order.getListServers - list of remtp place-order integration servers",
  "remtp.place-order.getActiveServer - remtp place-order integration active server",
  "remtp.place-order.commitRetries - number of attempts to connect to remtp place-order integration server",
  "remtp.list-recent-orders.port - remtp list-recent-orders integration server port number",
  "remtp.list-recent-orders.method - remtp list-recent-orders integration server method name to call",
  "remtp.recent-order-details.port - remtp recent-order-details integration server port number",
  "remtp.recent-order-details.method - remtp recent-order-details integration server method name to call",
  "remtp.query-back-order.port - remtp query-back-order integration server port number",
  "remtp.query-back-order.method - remtp query-back-order integration server method name to call",
  "remtp.back-order-cancellation.port - remtp back-order-cancellation integration server port number",
  "remtp.back-order-cancellation.method - remtp back-order-cancellation integration server method name to call",
  "remtp.batch.size - maximum number of records processed per batch",
  "remtp.batch.blockSize - maximum number of records processed per batch",
  "remtp.batch.aggregatorSize - number of records for processing in batch aggregator phase",
  "remtp.batch.wait - waiting time between processors in milliseconds",
  "remtp.control.retries - number of attempts to connect to remtp server",
  "remtp.control.wait - waiting time between connection retry to remtp server in milliseconds"
  ]