#%RAML 1.0 Library

types:
  properties-request:
    type: object
    properties:
      operation:
        description: Specify the operation that you want to apply
        enum: [read]
        required: false
        example: read
      apiNames:
        type: array
        items: string
        required: true
        displayName: List of api names
        description: List of api names to read properties for
        example: ["b2b-foe-bidwh-system-api"]
      configFiles:
        type: array
        items: string
        required: false
        displayName: List of config property files
        description: List of property files of the api for all environments
        example: ["local-properties.yaml","dev-properties.yaml"]
        